import{a as b,i as h}from"./assets/vendor-22aaac4a.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const s of a.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function r(t){if(t.ep)return;t.ep=!0;const a=n(t);fetch(t.href,a)}})();const v="42175181-9f2e4ea0c75ffabf50c3ef9f9";async function E(e,o=1){const n=`https://pixabay.com/api/?key=${v}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=15`;try{return(await b.get(n)).data.hits}catch(r){throw r}}function I(e,o){e.innerHTML="";const n=document.createDocumentFragment();o.forEach(r=>{const{largeImageURL:t,webformatURL:a,tags:s,likes:u,views:f,comments:g,downloads:y}=r,i=document.createElement("div");i.classList.add("image-card"),i.innerHTML=`
            <a href="${t}" data-lightbox="image-set" data-title="${s}">
                <img src="${a}" alt="${s}">
                <div class="info">Likes: ${u}, Views: ${f}, Comments: ${g}, Downloads: ${y}</div>
            </a>
        `,n.appendChild(i)}),e.appendChild(n)}function C(e,o){const n=document.createDocumentFragment();o.forEach(r=>{const{largeImageURL:t,webformatURL:a,tags:s,likes:u,views:f,comments:g,downloads:y}=r,i=document.createElement("div");i.classList.add("image-card"),i.innerHTML=`
            <a href="${t}" data-lightbox="image-set" data-title="${s}">
                <img src="${a}" alt="${s}">
                <div class="info">Likes: ${u}, Views: ${f}, Comments: ${g}, Downloads: ${y}</div>
            </a>
        `,n.appendChild(i)}),e.appendChild(n)}function B(){new SimpleLightbox(".gallery a").refresh()}const c=document.querySelector(".gallery"),R=document.getElementById("loader"),S=document.getElementById("search-form"),L=document.getElementById("load-more"),q=document.getElementById("loading-indicator");L.style.display="none";let d=1,$="";function x(e){h.success({title:"Success",message:e,position:"topRight"})}function p(e){h.error({title:"Error",message:e,position:"topRight"})}function l(e){L.style.display=e?"block":"none"}function m(e){R.style.display=e?"block":"none",q.style.display=e?"block":"none"}async function M(){const e=c.querySelector(".image-card").getBoundingClientRect().height;window.scrollBy({top:2*e,left:0,behavior:"smooth"})}async function w(e,o){try{m(!0);const n=await E(e,o);n.length>0?(o===1?I(c,n):C(c,n),x(`Was found: ${n.length} images`),B(),n.length<15?(p("We are sorry, but you have reached the end of search results."),l(!1)):l(!0),M()):(c.innerHTML="",p(`Sorry, there are no images matching your search query "${e}". Please try again!`),l(!1))}finally{m(!1)}}S.addEventListener("submit",async function(e){e.preventDefault(),l(!1);const o=document.getElementById("query").value.trim();if(!o){h.warning({title:"Warning",message:"Please enter a search query."});return}$=o,d=1,await w(o,d)});L.addEventListener("click",async function(){try{m(!0),d++,await w($,d)}catch{p("Failed to fetch additional images.")}finally{m(!1)}});
//# sourceMappingURL=commonHelpers.js.map
